version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - data_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: drone-tr-server
      MYSQL_USER: drone-tr-server
      MYSQL_PASSWORD: drone-tr-server

  php:
    build: .
    ports:
      - '8000:80'
    depends_on:
      - db
    volumes:
      - data_php:/var/www/html
    environment:
      DB_SERVER: db
      DB_DB: drone-tr-server
      DB_USER: drone-tr-server
      DB_PASSWORD: drone-tr-server


volumes:
  data_db:
  data_php: